#ifndef ESPTESTING_COMMON_SENSOR_INTERFACE_H
#define ESPTESTING_COMMON_SENSOR_INTERFACE_H

#include <freertos/portmacro.h>
#include "stdint.h"
#include "esp_check.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"


template <typename T>
class CommonSensorInterface{
public:
    //get sensor readings
    virtual esp_err_t get_readings(T &store) = 0;
    //get last error generated by the class
    virtual esp_err_t get_last_error() = 0;
};

template <typename T>
class FixedRateSensorInterface: public CommonSensorInterface<T>{
public:
    //create task that samples at fixed rate giving the task name and the sampling rate in milliseconds
    virtual esp_err_t start_sampling(const char* task_name, uint64_t &sampling_rate) = 0;
    //destroy task that samples at fixed rate
    virtual esp_err_t stop_sampling() = 0;
    //get the sampling rate in milliseconds
    virtual esp_err_t get_sampling_rate(uint64_t &millis) = 0;
    //check if the sampling is active by returning ESP_OK
    virtual esp_err_t get_sampling_status() = 0;
};

#endif ESPTESTING_COMMON_SENSOR_INTERFACE_H